### ISSUE TITLE
スタイルの修正（無理せずで大丈夫です）

### ISSUE THREAD

**Issue by ItsukiOtsubo** [sasakiy84/ndl-hackathon-2023#2]
スタイルで直せたらいいな、という点をまとめました。
イベントも終了しましたし、みなさまお忙しいと思うので無理せず、気が向いたらお願いします。

- [x] 「トップページに使った画像のクレジット」の下に20pxマージン追加
- [x] トップページの画像クレジット情報ページの、上下余白調整

**プログレスインジゲーター**
- [x] 1問目の質問ページで、赤い目盛りを1問目状態で表示
- [x] 回答確認ページでの地の色を質問ページと揃える（#F9F7F3）

**減点ポップアップ**
- [x] ページ上部に固定されているので、ブラウザに対して固定する（もっとヒントを表示の時に見えなくなってしまう）
- [x] 表示時間をもう少し短く

**総合得点ページ**
- [x] ブロンズマスターのメダル画像がリンク切れ（スペル違いが原因のようです。画像ファイル名は「medal_bronze.svg」、コードはアールがエルでした）

**スマホレイアウト**
- [x] トップページの画像は画面幅を狭くした時に中央部分を表示する
- [x] トップページと総合得点ページの「ジャパンサーチとは」はできればロゴを上にする
- [x] スマホで見るとサーチくんがガビってる？（表示はされてるので深追いせずで大丈夫です）

**Comment by sasakiy84** [comment]
@ItsukiOtsubo 
サーチ君は、すべての画像がガビってるのでしょうか？一部画像だけでしょうか？

**Comment by ItsukiOtsubo** [comment]
@sasakiy84 
回るサーチくん（GIF）以外がガビっているようです。
どれも形式はSVGです。もし、違う形式で差し替えの方が対応しやすければ、書き出します。

**Comment by sasakiy84** [comment]
なんでsvgなのにガビガビになるんでしょう…
自分のおんぼろスマホでは確認できなかったので、大坪さんのスマホでガビガビにならない画像を出力してもらって、それに差し替える形で対応したいです。なので、書き出しをお願いします

**Comment by ItsukiOtsubo** [comment]
諸々直していただいて、ありがとうございます！

SVGなのに、なんででしょうね（先日STUDIOでも同じようなことが起きて？？でした）
画像2点、GIFで書き出してプッシュしました。こちらでお願いいたします。

jpskun_incorrect.gif
jpskun_question.gif

加えて、

- [ ] 減点ポップアップがスマホ表示時に右側が見切れる
が起きていたので、お伝えします。

![IMG-1213](https://user-images.githubusercontent.com/115970632/221346426-fdfafe05-a99e-41ed-ad33-2ef08e77688e.PNG)

スタイル上の課題はこれでクリアです。

**Comment by sasakiy84** [comment]
ご指摘いただいた点修正しました。確認できましたらcloseしちゃってください
